cmd_drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.o := /home/brett/Desktop/toolchains/arm-cortex_a9-linux-gnueabihf-linaro_4.7.4-2014.01/bin/arm-cortex_a9-linux-gnueabihf-gcc -Wp,-MD,drivers/gpu/mali400/r3p2/mali/.__malidrv_build_info.o.d  -nostdinc -isystem /home/brett/Desktop/toolchains/arm-cortex_a9-linux-gnueabihf-linaro_4.7.4-2014.01/bin/../lib/gcc/arm-cortex_a9-linux-gnueabihf/4.7.4/include -I/home/brett/shifted/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-exynos/include -Iarch/arm/plat-s5p/include -Iarch/arm/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/linux/license/gpl -DMALI_FAKE_PLATFORM_DEVICE=1 -DPROFILING_SKIP_PP_JOBS=0 -DPROFILING_SKIP_PP_AND_GP_JOBS=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP=0 -DMALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS=0 -DMALI_STATE_TRACKING=1 -DMALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=16 -DUSING_GPU_UTILIZATION=1 -DMALI_UPPER_HALF_SCHEDULING -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/../../ump/include/ump -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/include -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/common -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/linux -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/platform -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/../ump/include -I/home/brett/shifted/drivers/gpu/mali400/r3p2/mali/include/linux/mali -DSVN_REV_STRING=\"\"    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(__malidrv_build_info)"  -D"KBUILD_MODNAME=KBUILD_STR(mali)" -c -o drivers/gpu/mali400/r3p2/mali/.tmp___malidrv_build_info.o drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.c

source_drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.o := drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.c

deps_drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.o := \

drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.o: $(deps_drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.o)

$(deps_drivers/gpu/mali400/r3p2/mali/__malidrv_build_info.o):
